<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns:File_Request="http://www.tibco.com/schemas/File Palette/Resources/Schemas/Service/File_Request"
	 xmlns:Header="http://www.tibco.com/schemas/XML Palette/Resources/Schemas/Common//Header"
	 targetNamespace="http://www.tibco.com/schemas/File Palette/Resources/Schemas/Service/File_Request"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:import namespace="http://www.tibco.com/schemas/XML Palette/Resources/Schemas/Common//Header"/>
	<xs:element name="File_Request">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Header:Header"/>
				<xs:element ref="File_Request:Body"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Body">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sourcePath" type="xs:string"/>
				<xs:element name="sourceFileName" type="xs:string"/>
				<xs:element name="message" type="xs:string"/>
<xs:element name="outputPath" type="xs:string"/>
				<xs:element name="outputFileName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>